# Imports
from ui_add_everyday_project import Ui_add_everyday_project
from ui_add_new_project import Ui_add_new_project
from ui_add_programming_project import Ui_add_programming
from ui_archive_viewer import Ui_archive_viewer
from ui_everyday_viewer import Ui_everyday_viewer
from ui_programming_viewer import Ui_programming_viewer
# from


